CREATE ROLE migrator WITH ENCRYPTED PASSWORD 'm1gr4t0r' LOGIN;
CREATE ROLE footprints WITH ENCRYPTED PASSWORD 'f33tst1nk' LOGIN NOINHERIT;
CREATE ROLE footprints_reader WITH ENCRYPTED PASSWORD 'f33tst1nk_r34d' LOGIN NOINHERIT;